# Generated by Django 5.0.6 on 2026-05-13 14:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_comparepartner_comparesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comparepartner',
            name='unique_user_partner',
        ),
        migrations.AddField(
            model_name='song',
            name='mb_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='song',
            name='mb_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='comparepartner',
            unique_together={('user', 'partner_username')},
        ),
    ]
